site_name: InMo Docs
site_author: Ovsiannikov Aleksei
site_description: >-
    Single documentation place for all Insanus Mokrassar libraries
site_url: https://docs.inmo.dev/
repo_name: InsanusMokrassar/docs
repo_url: https://github.com/InsanusMokrassar/docs

nav:
    - Home: 'index.md'
    - 'MicroUtils':
          - 'micro_utils/index.md'
    - 'Telegram Bot API':
        - 'tgbotapi/index.md'
        - KDocs: 'https://tgbotapi.inmo.dev'
        - 'tgbotapi/faq.md'
        - Introduction:
            - 'tgbotapi/introduction/before-any-bot-project.md'
            - 'tgbotapi/introduction/including-in-your-project.md'
            - 'tgbotapi/introduction/proxy-setup.md'
            - 'tgbotapi/introduction/first-bot.md'
        - Guides:
            - 'tgbotapi/guides/keyboards.md'
        - Updates retrieving:
            - 'tgbotapi/updates/updates-filters.md'
            - 'tgbotapi/updates/long-polling.md'
            - 'tgbotapi/updates/webhooks.md'
            - 'tgbotapi/updates/heroku.md'
        - Logic handling: 'tgbotapi/logic/'
        - DSLs: 'tgbotapi/dsls/'
        - PlaguBot (TBD):
              - 'tgbotapi/plagubot/'
    - 'Krontab':
        - 'krontab/index.md'
        - KDocs: 'https://krontab.inmo.dev/'
        - Introduction:
            - 'krontab/introduction/including-in-project.md'
            - 'krontab/introduction/how-to-use.md'
            - 'krontab/introduction/faq.md'
        - Describing:
            - 'krontab/describing/string-format.md'
            - 'krontab/describing/krontabscheduler.md'
    - 'KSLog':
        - 'kslog/index.md'
        - KDocs: 'https://kslog.inmo.dev/'
        - 'kslog/setup.md'
        - 'kslog/logging.md'
    - 'Navigation':
          - 'navigation/index.md'

use_directory_urls: false

theme:
    name: material
    logo: /resources/images/logo.png
    favicon: /resources/images/favicon.png
    palette:
        - scheme: default
          primary: teal
          accent: cyan
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: blue grey
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    hljs_languages:
        - yaml
        - kotlin
        - javascript
        - xml
        - groovy
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        # - navigation.instant
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
    font:
        text: Roboto
        code: Roboto Mono
#    icon:
#        annotation: material/arrow-right-circle

markdown_extensions:
    - toc:
          permalink: True
    - smarty
    - callouts
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html

plugins:
    - search
    - autorefs
    - include_dir_to_nav
    - mermaid2:
        arguments:
          theme: |
            ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

# Customization
extra:
    analytics:
        provider: google
        property: G-615VY8CQSM
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/InsanusMokrassar
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/r/insanusmokrassar
        - icon: fontawesome/brands/telegram
          link: https://t.me/InsanusMokrassar
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/InsanusMokrassa
#    annotate:
#        json: [.s2]
extra_css:
    - /resources/stylesheets/navigation.css

mermaid:
    javascript:
        - /resources/js/mermaid.min.js
        - /resources/js/mermaid_dark_light_switcher.js
